### ISSUE TITLE
Insecure Docker Registry for the required images

### ISSUE THREAD

**Issue by Arwany** [Woorank/vagrant-mesos-cluster#68]
Hi,

I have tried to get this repo working without pulling the images from the docker hub, but from my own private repository.

First I have pulled the images to my repository and labeled them accordingly and then pushed them, so that they can be pulled from it.

After that I added a new step to the docker installation (private.yml) with the following content:

``` 
---
- name: Enable Private Repository
  shell: echo 'DOCKER_OPTS="--restart=true --insecure-registry 192.168.99.100:5000"' >> /etc/default/docker; service docker restart;
```
I then changed the images accordingly to be pulled from my private registry, for example:

```
---
haproxy_version: "1.5.14"
haproxy_docker_image: "192.168.99.100:5000/mesoscloud/haproxy:{{haproxy_version}}-ubuntu-14.04"
haproxy_name: "haproxy"

```

Note: This is the registry IP: 192.168.99.100

Now when I try vagrant up, I get the following error:

```
TASK: [zookeeper | Make sure zookeeper is running and config is up-to-date] ***
failed: [100.0.10.11] => {"error": "DockerException(\"HTTPS endpoint unresponsive and insecure mode isn't enabled.\",)", "failed": true}
msg: Failed to pull the specified image: 192.168.99.100:5000/mesoscloud/zookeeper:3.4.6-ubuntu-14.04

FATAL: all hosts have already failed -- aborting
```

I sshed into the machine, and could pull the image with the command

```
docker pull 192.168.99.100:5000/mesoscloud/zookeeper:3.4.6-ubuntu-14.04
```

What am I doing wrong? Thanks for the help.

**Comment by satblip** [comment]
Hi Arwany,

You've to add the option `--allow-insecure-ssl` to your `DOCKER_OPTS` and it should do the trick. Your certificate on your own registry seems to be selfsigned.
